# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f20b1f895a3107b972b5b9cda707c45a309f94e9640e6951d63f8c87a61ed6f9ff53d7e60e1b4d8a0fbe3f29ce9bc69d9e60a48c6d9e6f34baf5b59e57923cec

test:
  secret_key_base: fab44d2097d856fef3277463f11146b0b84b06e1bda7f12c8a034eba3ffd22afd9e4621752e20baf282b8dc705972942c477c578babffeccac73f9e785f0e538

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
